language: python
python:
  - "3.6"

script: echo 'all test are passing'

install:
    - nvm install 8
    - pip install awscli
    pythoh --version

after_success:
  - cd webapp
  - pip install zappa
  - pip install -r requirements.txt
  - zappa update dev
  - cd ../client
  - sh ./deploy-client.sh
